version: "3.0"
services:
  prestamype-tcd-api:
    container_name: prestamype-tcd-api
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    # command: yarn start:dev
    ports:
      - "3000:3000"
    command: ["start:dev"]
    volumes:
      - .:/app
      # - /app/node_modules
    env_file:
      - .env