version: "3.0"
services:
  prestamype-tcd-api:
    ports:
      - "3000:3000"
    container_name: prestamype-tcd-api
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    volumes:
      - .:/app
      - /app/node_modules
    command: ["start:dev"]